// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesMostenAPI.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoviesMostenAPI.Migrations
{
    [DbContext(typeof(FilmeSerieContext))]
    [Migration("20250809194123_listaDeGeneros")]
    partial class listaDeGeneros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoviesMostenAPI.Models.FilmeSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<List<string>>("Genero")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Gostei")
                        .HasColumnType("integer");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NaoGostei")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FilmeSeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Os irmãos Sam e Dean Winchester encaram cenários sinistros caçando monstros, mas velhos truques, armas e esconderijos não funcionam mais. Traídos pelos amigos, os irmãos precisam colaborar enquanto enfrentam novos inimigos.",
                            Genero = new List<string> { "Terror", "Drama", "Suspense" },
                            Gostei = 25,
                            Imagem = "https://m.media-amazon.com/images/M/MV5BMDFmMGZmMGItNGRjNC00NjVjLWI5ODEtNzhjMTE5MmJhN2FkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            NaoGostei = 8,
                            Titulo = "Supernatural"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Sucesso entre os livros mais vendidos, a série de obras 'A Song of Ice and Fire', de George R.R. Martin, é levada à tela quando HBO decide navegar a fundo pelo gênero e recriar a fantasia medieval épica. Este é o retrato de duas famílias poderosas - reis e rainhas, cavaleiros e renegados, homens honestos e mentirosos - disputando um jogo mortal pelo controle dos Sete Reinos de Westeros para assumir o Trono de Ferro. A série foi filmada em Malta e no norte da Irlanda, tendo participação do escritor dos livros.",
                            Genero = new List<string> { "Aventura", "Fantasia" },
                            Gostei = 16,
                            Imagem = "https://m.media-amazon.com/images/M/MV5BMTNhMDJmNmYtNDQ5OS00ODdlLWE0ZDAtZTgyYTIwNDY3OTU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            NaoGostei = 5,
                            Titulo = "Game of Thrones"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Loki, o irmão de Thor, ganha acesso ao poder ilimitado do cubo cósmico ao roubá-lo de dentro das instalações da S.H.I.E.L.D. Nick Fury, o diretor desta agência internacional que mantém a paz, logo reúne os únicos super-heróis que serão capazes de defender a Terra de ameaças sem precedentes. Homem de Ferro, Capitão América, Hulk, Thor, Viúva Negra e Gavião Arqueiro formam o time dos sonhos de Fury, mas eles precisam aprender a colocar os egos de lado e agir como um grupo em prol da humanidade.",
                            Genero = new List<string> { "Ação", "Aventura" },
                            Gostei = 30,
                            Imagem = "https://br.web.img2.acsta.net/medias/nmedia/18/89/43/82/20052140.jpg",
                            NaoGostei = 12,
                            Titulo = "Os Vingadores"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Breaking Bad é uma série de televisão americana criada e produzida por Vince Gilligan. Ela retrata a vida do químico Walter White, um homem brilhante frustrado em dar aulas para adolescentes do ensino médio enquanto lida com um filho sofrendo de paralisia cerebral, uma esposa grávida e dívidas intermináveis. White, então, é diagnosticado com um câncer no pulmão - o que o leva a sofrer um colapso emocional e abraçar uma vida de crimes para pagar suas dívidas hospitalares e dar uma boa vida aos seus filhos.",
                            Genero = new List<string> { "Drama", "Crime" },
                            Gostei = 26,
                            Imagem = "https://delfos.net.br/wp-content/uploads/2017/05/860343-03-05-17-35.jpg",
                            NaoGostei = 7,
                            Titulo = "Breaking Bad"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "John Wick é uma franquia de mídia de suspense e ação neo-noir americana criada pelo roteirista Derek Kolstad e estrelada por Keanu Reeves como John Wick, um ex-assassino que é forçado a voltar ao submundo do crime que havia abandonado.",
                            Genero = new List<string> { "Ação", "Crime" },
                            Gostei = 23,
                            Imagem = "https://m.media-amazon.com/images/I/71+k2-r7vQL._UF894,1000_QL80_.jpg",
                            NaoGostei = 2,
                            Titulo = "John Wick"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
